# Generated by Django 3.2.3 on 2021-07-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerprofile',
            name='contact_person',
            field=models.CharField(default='HR', max_length=100),
        ),
        migrations.AddField(
            model_name='employeerprofile',
            name='email',
            field=models.CharField(max_length=100, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='employeerprofile',
            name='phone',
            field=models.CharField(max_length=12, null=1),
            preserve_default=1,
        ),
    ]
