# Generated by Django 3.2.3 on 2021-07-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_auto_20210719_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerprofile',
            name='username',
            field=models.CharField(default='employer', max_length=120, null=0),
        ),
    ]
