# Generated by Django 3.2.3 on 2021-07-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_employeerprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerprofile',
            name='password',
            field=models.CharField(default='employer', max_length=120, null=0),
        ),
    ]
