# Generated by Django 3.2.3 on 2021-07-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_employeerprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerprofile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='role',
        ),
    ]
