# Generated by Django 3.2.3 on 2021-07-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_alter_job_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employeer',
        ),
    ]
