# Generated by Django 3.2.3 on 2021-07-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_remove_job_employeer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationjob',
            name='jobseeker_id',
        ),
        migrations.AddField(
            model_name='applicationjob',
            name='address',
            field=models.CharField(max_length=500, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='applicationjob',
            name='applied_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applicationjob',
            name='email',
            field=models.CharField(max_length=100, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='applicationjob',
            name='experience',
            field=models.CharField(max_length=120, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='applicationjob',
            name='name',
            field=models.CharField(max_length=120, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='applicationjob',
            name='phone',
            field=models.CharField(max_length=12, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='applicationjob',
            name='qualifications',
            field=models.CharField(max_length=120, null=1),
            preserve_default=1,
        ),
    ]
