# Generated by Django 3.2.3 on 2021-07-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_auto_20210722_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationjob',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
